import os
import streamlit as st
from src.graph.workflow import build_workflow

# Inject Streamlit Cloud Secrets into environment variables for LangChain/Groq
if hasattr(st, "secrets"):
    for key, value in st.secrets.items():
        os.environ[str(key)] = str(value)


# Page config
st.set_page_config(
    page_title = "ABIA - Business Intelligence Assistant",
    page_icon="📊",
    layout = "wide"
)

st.title("📊 ABIA: Agentic Business Intelligence Assistant")
st.caption("Ask natural language questions about sales, customer segments, products, and regional performance.")

# Initialize LangGraph workflow (Cached to prevent reloading on every click)
@st.cache_resource
def get_workflow():
    return build_workflow()

app = get_workflow()

# Sidebar Example Queries
st.sidebar.header("💡 Example Queries")
example_query = st.sidebar.radio(
    "Click an example to test:",
    [
        "Total revenue by region",
        "Total revenue by product category in North America",
        "Revenue generated by churned vs active customers",
        "Top 5 products by total revenue",
        "Total revenue by product category for Premium customers in Europe"
    ]
)

# Text Input Box
user_query = st.text_input("Enter your question:", value=example_query)

if st.button("🚀 Run Query", type="primary") and user_query:
    with st.spinner("Analyzing schema, planning query, and computing Pandas results..."):
        initial_state = {
            "user_query": user_query,
            "retry_count": 0,
            "error": None
        }

        # Invoke Graph
        final_state = app.invoke(initial_state)

        if final_state.get("error"):
            st.error(f"❌ Execution Error: {final_state['error']}")
        else:
            # Render Markdown Result Table
            st.markdown(final_state["formatted_result"])

            # Expandable View for LLM Query Plan
            if final_state.get("plan"):
                with st.expander("🔍 View Generated Execution Plan (JSON)"):
                    st.json(final_state["plan"].model_dump())