import os

import pandas as pd
import plotly.express as px
import streamlit as st

from src.graph.workflow import build_workflow

# -------------------------------------------------------------
# 1. STREAMLIT CLOUD SECRETS HANDLER
# -------------------------------------------------------------
if hasattr(st, "secrets"):
    for key, value in st.secrets.items():
        os.environ[str(key)] = str(value)


# -------------------------------------------------------------
# 2. PAGE CONFIGURATION
# -------------------------------------------------------------
st.set_page_config(
    page_title="ABIA - Business Intelligence Assistant", page_icon="📊", layout="wide"
)

# -------------------------------------------------------------
# 3. CUSTOM CSS STYLING
# -------------------------------------------------------------
st.markdown(
    """
    <style>
    div[data-testid="stCaptionContainer"] p {
        font-size: 18px !important;
    }
    label[data-testid="stWidgetLabel"] p {
        font-size: 22px !important;
        font-weight: 700 !important;
    }
    div[data-testid="stTextInput"] input {
        font-size: 18px !important;
        height: 60px !important;
        padding: 12px 18px !important;
        border-radius: 10px !important;
    }
    div[data-testid="stSidebar"] div[data-testid="stRadio"] > div {
        gap: 20px !important;
    }
    div[data-testid="stSidebar"] div[data-testid="stRadio"] label {
        margin-bottom: 10px !important;
        padding: 6px 10px !important;
    }
    /* Metric Card Styling */
    div[data-testid="stMetricValue"] {
        font-size: 28px !important;
        font-weight: 800 !important;
        color: #1E88E5 !important;
    }
    </style>
""",
    unsafe_allow_html=True,
)

# -------------------------------------------------------------
# 4. HEADER & WORKFLOW INITIALIZATION
# -------------------------------------------------------------
st.title("📊 ABIA: Agentic Business Intelligence Dashboard")
st.caption(
    "Ask natural language questions to generate instant executive insights, KPI dashboards, and visual analytics."
)


@st.cache_resource
def get_workflow():
    return build_workflow()


app = get_workflow()

# -------------------------------------------------------------
# 5. SIDEBAR EXAMPLE QUESTIONS
# -------------------------------------------------------------
st.sidebar.header("💡 Example Dashboards & Queries")
example_query = st.sidebar.radio(
    "Click an example to test:",
    [
        "Total revenue by region",
        "What is the revenue trend for Asia compared to Europe?",
        "Top 5 products by profit margin",
        "Revenue generated by churned vs active customers",
        "Revenue share by sales channel",
        "Total revenue by product category for Premium customers in Europe",
    ],
)

# User Query Input Box
user_query = st.text_input("Enter your question:", value=example_query)


# -------------------------------------------------------------
# 6. EXECUTIVE KPI METRIC CARDS RENDERER (DYNAMIC)
# Renders 4 high-level summary cards at the top of responses
# -------------------------------------------------------------
def render_kpi_cards(df: pd.DataFrame):
    """Dynamically parses ANY returned columns and renders adaptive KPI cards."""
    if df is None or df.empty:
        return

    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    text_cols = df.select_dtypes(
        include=["object", "category", "datetime"]
    ).columns.tolist()

    if not numeric_cols:
        return

    st.markdown("### 📌 Executive Summary KPIs")
    # Dynamically create 2 to 4 KPI card columns
    num_cards = min(len(numeric_cols) + (1 if text_cols else 0), 4)
    cols = st.columns(num_cards)

    col_idx = 0

    # Card 1: Primary Metric
    m1 = numeric_cols[0]
    m1_name = m1.replace("_", " ").title()
    if any(k in m1.lower() for k in ["rate", "margin", "pct"]):
        cols[col_idx].metric(label=f"📊 Avg {m1_name}", value=f"{df[m1].mean():.1f}%")
    elif any(k in m1.lower() for k in ["price", "revenue", "cost", "profit"]):
        cols[col_idx].metric(label=f"💵 Total {m1_name}", value=f"${df[m1].sum():,.2f}")
    else:
        cols[col_idx].metric(label=f"📦 Total {m1_name}", value=f"{df[m1].sum():,.0f}")
    col_idx += 1

    # Card 2: Secondary Metric (if present)
    if len(numeric_cols) > 1 and col_idx < num_cards:
        m2 = numeric_cols[1]
        m2_name = m2.replace("_", " ").title()
        if any(k in m2.lower() for k in ["rate", "margin", "pct"]):
            cols[col_idx].metric(
                label=f"📈 Avg {m2_name}", value=f"{df[m2].mean():.1f}%"
            )
        elif any(k in m2.lower() for k in ["price", "revenue", "cost", "profit"]):
            cols[col_idx].metric(
                label=f"💰 Total {m2_name}", value=f"${df[m2].sum():,.2f}"
            )
        else:
            cols[col_idx].metric(
                label=f"📦 Total {m2_name}", value=f"{df[m2].sum():,.0f}"
            )
        col_idx += 1

    # Card 3: Third Metric or Average (if present)
    if len(numeric_cols) > 2 and col_idx < num_cards:
        m3 = numeric_cols[2]
        m3_name = m3.replace("_", " ").title()
        cols[col_idx].metric(label=f"📊 Avg {m3_name}", value=f"${df[m3].mean():,.2f}")
        col_idx += 1

    # Card 4: Categorical Group Count / Entity Scope
    if text_cols and col_idx < num_cards:
        entity_name = text_cols[0].replace("_", " ").title()
        cols[col_idx].metric(label=f"🏷️ {entity_name} Analyzed", value=f"{len(df):,}")

    st.divider()


# -------------------------------------------------------------
# 7. DYNAMIC PLOTLY CHART ENGINE
# -------------------------------------------------------------
def render_dynamic_plotly_chart(df: pd.DataFrame, plan):
    if df is None or df.empty or len(df.columns) < 2:
        return

    chart_type = getattr(plan, "chart_type", "bar") if plan else "bar"
    if chart_type == "table_only":
        return

    numeric_cols = df.select_dtypes(include=["number"]).columns.tolist()
    text_time_cols = df.select_dtypes(
        include=["object", "category", "datetime"]
    ).columns.tolist()

    if not numeric_cols:
        return

    st.markdown("### 📈 Visual Analytics")

    # 1. PIE / DONUT CHART
    if chart_type == "pie" and text_time_cols and numeric_cols:
        fig = px.pie(
            df,
            names=text_time_cols[0],
            values=numeric_cols[0],
            hole=0.4,
            title=f"Distribution Share: {numeric_cols[0].replace('_', ' ').title()} by {text_time_cols[0].title()}",
        )
        st.plotly_chart(fig, use_container_width=True)

    # 2. LINE / TREND CHART (Multi-series support with Auto-Aggregation)
    elif chart_type == "line" and text_time_cols and numeric_cols:
        time_col = text_time_cols[0]
        # Identify time-based column
        for col in text_time_cols:
            if any(
                t in col.lower() for t in ["month", "year", "date", "day", "quarter"]
            ):
                time_col = col
                break

        metric = numeric_cols[0]

        if len(text_time_cols) >= 2:
            group_col = next(c for c in text_time_cols if c != time_col)

            # Collapse raw order rows into 1 sum per month per region
            plot_df = df.groupby([time_col, group_col])[metric].sum().reset_index()
            # Sort by time to ensure smooth line rendering
            plot_df = plot_df.sort_values(by=time_col)

            fig = px.line(
                plot_df,
                x=time_col,
                y=metric,
                color=group_col,
                markers=True,
                title=f"Trend Comparison: {metric.replace('_', ' ').title()} by {group_col.title()} over {time_col.title()}",
            )
        else:
            plot_df = (
                df.groupby(time_col)[metric]
                .sum()
                .reset_index()
                .sort_values(by=time_col)
            )
            fig = px.line(
                plot_df,
                x=time_col,
                y=metric,
                markers=True,
                title=f"Trend Analysis: {metric.replace('_', ' ').title()} over {time_col.title()}",
            )
        st.plotly_chart(fig, use_container_width=True)

    # 3. AREA CHART
    elif chart_type == "area" and text_time_cols and numeric_cols:
        time_col = text_time_cols[0]
        fig = px.area(
            df,
            x=time_col,
            y=numeric_cols[0],
            color=text_time_cols[1] if len(text_time_cols) >= 2 else None,
            title=f"Volume Growth: {numeric_cols[0].replace('_', ' ').title()} over {time_col.title()}",
        )
        st.plotly_chart(fig, use_container_width=True)

    # 4. SCATTER PLOT
    elif chart_type == "scatter" and len(numeric_cols) >= 2:
        fig = px.scatter(
            df,
            x=numeric_cols[0],
            y=numeric_cols[1],
            color=text_time_cols[0] if text_time_cols else None,
            size=numeric_cols[0],
            hover_data=df.columns,
            title=f"Correlation: {numeric_cols[0].replace('_', ' ').title()} vs {numeric_cols[1].replace('_', ' ').title()}",
        )
        st.plotly_chart(fig, use_container_width=True)

    # 5. BAR CHART (Default)
    elif text_time_cols and numeric_cols:
        if len(text_time_cols) >= 2:
            fig = px.bar(
                df,
                x=text_time_cols[0],
                y=numeric_cols[0],
                color=text_time_cols[1],
                barmode="group",
                title=f"{numeric_cols[0].replace('_', ' ').title()} Breakdown by {text_time_cols[0].title()} & {text_time_cols[1].title()}",
            )
        else:
            fig = px.bar(
                df,
                x=text_time_cols[0],
                y=numeric_cols[0],
                color=text_time_cols[0],
                title=f"{numeric_cols[0].replace('_', ' ').title()} by {text_time_cols[0].title()}",
            )
        st.plotly_chart(fig, use_container_width=True)


# -------------------------------------------------------------
# 8. MAIN EXECUTION BLOCK
# -------------------------------------------------------------
if st.button("🚀 Run Query & Generate Dashboard", type="primary") and user_query:
    with st.spinner(
        "Analyzing schema, planning multi-metric execution, and running Pandas calculations..."
    ):
        initial_state = {"user_query": user_query, "retry_count": 0, "error": None}

        final_state = app.invoke(initial_state)

        if final_state.get("error"):
            st.error(f"❌ Execution Error: {final_state['error']}")
        else:
            res_df = final_state.get("result_df")
            plan = final_state.get("plan")

            # 1. Render Top-Level KPI Summary Cards
            render_kpi_cards(res_df)

            # 2. Render Markdown Results & LLM Executive Insights
            st.markdown(final_state["formatted_result"])

            # 3. Render Dynamic Interactive Plotly Chart
            render_dynamic_plotly_chart(res_df, plan)

            # 4. Export CSV Button
            if res_df is not None and not res_df.empty:
                st.markdown("---")
                st.download_button(
                    label="📥 Export Result Table as CSV",
                    data=res_df.to_csv(index=False).encode("utf-8"),
                    file_name="abia_dashboard_export.csv",
                    mime="text/csv",
                )

            # 5. JSON Execution Plan Inspector
            if plan:
                with st.expander("🔍 View Generated Execution Plan (JSON)"):
                    st.json(plan.model_dump())
